import Config

# Dev-machine secrets (BGG token + R2 credentials) for the one-time D-02
# catalog seed pipeline. Gitignored; a fresh clone and CI both still compile
# without it. Copy config/dev.secret.exs.example to create it locally.
secret_config_path = Path.expand("dev.secret.exs", __DIR__)

# The CSP img-src origin (01-06/T-01-28) — falls back to the same
# placeholder host config/test.exs uses so a fresh clone still boots with
# no secrets configured. config/runtime.exs's dev block overrides this with
# the real R2_PUBLIC_BASE_URL (env var, then dev.secret.exs's Application
# config) once that compile-time config has actually been merged in — see
# the comment there for why this file alone can't do that resolution.
dev_image_origin =
  case System.get_env("R2_PUBLIC_BASE_URL") do
    nil ->
      "https://images.test.invalid"

    url ->
      uri = URI.parse(url)
      port_suffix = if uri.port in [nil, 80, 443], do: "", else: ":#{uri.port}"
      "#{uri.scheme}://#{uri.host}#{port_suffix}"
  end

# Configure your database
#
# Env-var-first Repo target (SEED-02): set DATABASE_URL inline for a single
# `mix` invocation to point this dev environment at another database (e.g. a
# tunnelled production instance) instead of the hardcoded local target below.
# See AGENTS.md's "Production data seeding" section for the full re-seed
# runbook. Left unset (the default), this resolves byte-identical to today's
# hardcoded local target. Sensitive-data-on-connection-error logging is
# forced off whenever the override is in effect, so a failed connection
# through a tunnel cannot print a production password into a terminal.
database_url = System.get_env("DATABASE_URL")

repo_target =
  if database_url do
    [url: database_url, show_sensitive_data_on_connection_error: false]
  else
    [
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "pukllay_club_dev",
      show_sensitive_data_on_connection_error: true
    ]
  end

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :pukllay_club, PukllayClub.Repo, [stacktrace: true, pool_size: 10] ++ repo_target

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pukllay_club, PukllayClubWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "I7y7nU8Rmdd9kND2FAWBKBDq1I0DDCf8CVE+owjGFG9Jbu/0s8aEsmWoofjtodDP",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pukllay_club, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pukllay_club, ~w(--watch)]}
  ]

config :pukllay_club, :image_origin, dev_image_origin

# Dev placeholder for the detail page's reservation CTA (plan 01.1-05) — not
# a real number. config/runtime.exs's :prod block raises instead of falling
# back to this value, so this placeholder can never reach production.
config :pukllay_club, :reservation_whatsapp_number, "5491100000000"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :pukllay_club, dev_routes: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

if File.exists?(secret_config_path) do
  import_config "dev.secret.exs"
end
